[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "gunicorn wsgi:application --workers 2 --timeout 120 --max-requests 1000 --max-requests-jitter 100 --preload --log-level=info"

[env]
PYTHONPATH = "/app"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
PYTHONHASHSEED = "random"